#########################
# PseudoSkyblock Config #
#########################

# DO NOT CHANGE THIS LINE! YOUR CONFIG WILL BE RESET UPON LOADING IF THIS LINE IS EDITED!
Version: 1


########
# Data #
########

# Data save interval (in seconds)
DataSaveInterval: 3


#################
# Custom Blocks #
#################

# Whether or not redstone will disable the autominers
AffectedByRedstone: true

# Auto Miner speed (in ticks)
AutoMinerSpeed: 300