#######################
#PseudoSpawners Config#
#######################

#DO NOT CHANGE THIS LINE! YOUR CONFIG WILL BE RESET UPON LOADING IF THIS LINE IS EDITED!
Version: 1


#####
#GUI#
#####

#Interface Name
InterfaceName: "&c&lPseudoSpawners"

#Last Page Button
#{page} = Page number
LastPageName: "Page {page}"
LastPageItem: Paper
#Number between 1-9
LastPageLocation: 2

#Next Page Button
#{page} = Page number
NextPageName: "Page {page}"
NextPageItem: Paper
#Number between 1-9
NextPageLocation: 8


##########
#Spawners#
##########

#What mob types are not allowed?
#List of possible mob types here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EntityType.html
Blacklist:
  - area_effect_cloud
  - armor_stand
  - arrow
  - boat
  - dragon_fireball
  - egg
  - ender_crystal
  - ender_pearl
  - ender_signal
  - evoker_fangs
  - experience_orb
  - fireball
  - giant
  - item_frame
  - leash_hitch
  - llama_spit
  - minecart
  - minecart_chest
  - minecart_command
  - minecart_furnace
  - minecart_hopper
  - minecart_mob_spawner
  - minecart_tnt
  - painting
  - primed_tnt
  - shulker_bullet
  - small_fireball
  - snowball
  - spectral_arrow
  - splash_potion
  - thrown_exp_bottle
  - trident
  - wither_skull


###########
#Mob Names#
###########

#What chat color should the mob type be?
Color: e

#What are the names of different mob types?
#List of possible mob types here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EntityType.html

#List in the following format:
#Names:
#  bat: "Bat"

Names: []