name: PseudoSpawners
author: PseudoResonance
main: io.github.pseudoresonance.pseudospawners.PseudoSpawners
version: 1.0.9
description: Adds the ability to collect and change spawner types
depend: [PseudoAPI]
commands:
  pseudospawners:
    description: PseudoSpawners Menu
  spawner:
    description: Alias for PseudoSpawners spawner
  editspawner:
    description: Alias for PseudoSpawners editspawner
permissions:
  pseudospawners.reset:
    description: Allows the player to reset the config
    default: op
  pseudospawners.reload:
    description: Allows the player to reload the plugin
    default: op
  pseudospawners.craft:
    description: Allows the player to craft spawners
    default: true
  pseudospawners.collect:
    description: Allows the player to collect spawners
    default: true
  pseudospawners.collect.nosilk:
    description: Allows the player to collect spawners without silk touch
    default: op
    children:
      pseudospawners.collect: true
  pseudospawners.modify:
    description: Allows the player to change spawner types
    default: true
  pseudospawners.spawner:
    description: Allows the player to change spawner types without an egg
    default: op
    children:
      pseudospawners.modify: true
  pseudospawners.spawn:
    description: Allows the player to spawn spawners
    default: op
  pseudospawners.edit:
    description: Allows the player to edit spawner data
    default: op
  pseudospawners.override:
    description: Allows the player to change override disallowed spawner types
    default: false
  pseudospawners.*:
    description: Gives the user all PseudoSpawners permissions
    default: op
    children:
      pseudospawners.reset: true
      pseudospawners.reload: true
      pseudospawners.collect.nosilk: true
      pseudospawners.spawner: true
      pseudospawners.override: true
      pseudospawners.craft: true
      pseudospawners.spawn: true
      pseudospawners.edit: true