name: ${project.artifactId}
author: PseudoResonance
main: io.github.pseudoresonance.pseudoskyblock.PseudoSkyblock
version: ${revision}
description: Adds various skyblock utilities
api-version: 1.13
depend: [PseudoAPI]
commands:
  pseudoskyblock:
    description: PseudoSkyblock Menu
permissions:
  pseudoskyblock.reload:
    description: Allows the player to reload the plugin
    default: op
  pseudoskyblock.reset:
    description: Allows the player to reset the config
    default: op
    children:
      pseudoskyblock.reload: true
  pseudoskyblock.reloadlocalization:
    description: Allows the player to reload the localization
    default: op
  pseudoskyblock.resetlocalization:
    description: Allows the player to reset the localization
    default: op
    children:
      pseudoskyblock.reloadlocalization: true
  pseudoskyblock.*:
    description: Gives the user all PseudoSkyblock permissions
    default: op
    children:
      pseudoskyblock.reset: true
      pseudoskyblock.resetlocalization: true